// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using USPresidentsWebAPI.Contexts;

namespace USPresidentsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190520004123_modify-column")]
    partial class modifycolumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("USPresidentsWebAPI.Entities.President", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthPlace");

                    b.Property<DateTime>("Birthday");

                    b.Property<DateTime?>("DeathDay");

                    b.Property<string>("DeathPlace");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Presidents");
                });
#pragma warning restore 612, 618
        }
    }
}
